# Generated by Django 6.0.3 on 2026-05-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userwithemail',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userwithemail',
            name='username',
        ),
    ]
