# Generated by Django 6.0.3 on 2026-03-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTypes',
            new_name='FoodType',
        ),
    ]
