# Generated by Django 6.0.3 on 2026-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_foodtypes_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='type_icon',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
