# Generated by Django 6.0.3 on 2026-04-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodtype_type_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background_image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
