# Generated by Django 6.0.3 on 2026-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
