# Generated by Django 6.0.3 on 2026-04-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurant_background_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_max_time',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='avg_min_time',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='food_types',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_types', models.ManyToManyField(to='api.foodtype')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_types',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_food_type', to='api.foodtype'),
        ),
    ]
