# Generated by Django 6.0.3 on 2026-05-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_city_state_college_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_college', to='api.college'),
        ),
    ]
