# Generated by Django 6.0.3 on 2026-05-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='api.foodtype'),
        ),
    ]
