# Generated by Django 6.0.3 on 2026-05-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_restaurant_food_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_types',
        ),
        migrations.AddField(
            model_name='food',
            name='food_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_types', to='api.foodtype'),
        ),
    ]
